Nerogar/OneTrainer

modules/trainer/GenericTrainer.py
On Ubuntu 20.04, using a string gives this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda/bin/tensorboard --logdir workspace/tensorboard --port 6006 --samples_per_plugin=images=100'
=> Use list of arguments instead of a string for Popen()

modules/modelSaver/BaseModelSaver.py, modules/ui/TrainUI.py, scripts/train.py
By putting converted values on the cpu we can avoid the slight bump in vram usage right before saving, which lets me fine tune SDXL in batches of 1 w/accumulation steps at 1024px on 24GB of vram.
Note - I'm running 532.03 which doesn't automatically swap vram to cpu when vram is low.
The other change was a small bug, `trainer.end()` is already checking the backup_before_save flag internally and skipping `trainer.end()` prevents the model from being saved.
Might fix https://github.com/Nerogar/OneTrainer/issues/28
Also, thanks for continuing on the StableTuner spirit, this is so much easier to hack about than kohya_ss.
=> Use less vram ram on save and fix minor issue where the model isn't saved if backup before save is disabled

modules/trainer/GenericTrainer.py, modules/ui/TrainUI.py, modules/util/args/TrainArgs.py, training_presets/#sd 1.5 LoRA.json, training_presets/#sd 1.5 embedding.json, training_presets/#sd 1.5 inpaint masked.json, training_presets/#sd 1.5 inpaint.json, training_presets/#sd 1.5 masked.json, training_presets/#sd 1.5.json, training_presets/#sd 2.0 inpaint LoRA.json, training_presets/#sd 2.0 inpaint.json, training_presets/#sd 2.1 LoRA.json, training_presets/#sd 2.1 embedding.json, training_presets/#sd 2.1.json, training_presets/#sdxl 1.0 LoRA.json, training_presets/#sdxl 1.0 inpaint LoRA.json, training_presets/#sdxl 1.0.json
UI switch for enabling the continued training of the last backup in the workspace folder. This switch follows all the proper UI syntax, with a tooltip, and saving correctly the JSON file. As well as working when starting directly from the /scripts.
If no backup is found, `base_model_name` and `extra_model_name` are left untouched.
=> Simple UI Switch for Continued Training

modules/modelSetup/BaseStableDiffusionXLSetup.py, modules/modelSetup/mixin/ModelSetupDebugMixin.py
Uses quick and dirty (but functioning!) method for latent-to-RGB conversion described here:
https://huggingface.co/blog/TimothyAlexisVass/explaining-the-sdxl-latent-space#direct-conversion-of-sdxl-latents-to-rgb-with-a-linear-approximation
I created a separate method for it to keep everything non-SDXL related intact (hopefully).
=> Add quick and dirty SDXL latent2rgb conversion

install.sh, start-ui.sh, update.sh
The "#!" is required at the start of scripts that run on unix-like systems. https://en.wikipedia.org/wiki/Shebang_(Unix). Without the !, "#/bin/bash" was being interpreted as a comment for whatever shell was currently running. On macOS, zsh is the default shell and so the script was running in zsh. The script is slightly incompatible with zsh so it was getting an error. Adding the ! fixes this.
=> Add ! to the start of all unix scripts

scripts/generate_captions.py
WD14_VIT_2 was not present in `generate_caption.py`, resulting not being usable from cli.
parse arg `--model WD14_VIT_2` to make it usable from cli
=> Add WDModel to generate_captions.py

install.sh
Ubuntu systems have python = python2, not python3. This lets you specify exactly which python you want to use, very helpful for these systems or any where you have multiple pythons installed (a user in the discord had exactly this problem). Also let venv path be specified while I was at it.
=> Allow python and venv paths to be specified.

modules/modelSetup/BasePixArtAlphaSetup.py, modules/modelSetup/BaseStableDiffusionSetup.py, modules/modelSetup/BaseStableDiffusionXLSetup.py, modules/modelSetup/BaseWuerstchenSetup.py, modules/modelSetup/StableDiffusionFineTuneVaeSetup.py, modules/modelSetup/mixin/ModelSetupDiffusionLossMixin.py, modules/ui/TrainingTab.py, modules/util/config/TrainConfig.py
This implements minimum SNR gamma, based off of the paper "Efficient Diffusion Training via Min-SNR Weighting Strategy" and referenced to the implementation in Kohya's sd-scripts.
Due to my own hardware limitations I am only able to test this on SD 1.5, and I don't exactly have any diverse datasets. I highly suggest testing this on other models, and further SD 1.5 testing, before merging. In the future it would be good to have some known test tensors to check loss modifications against, but that's a PR for another time.
=> Implement minimum SNR gamma

modules/model/StableDiffusionModel.py
Without this change, training with zero-terminal snr/v-predicion (and I guess epsilon predicion) won't start due to error below.
```
Traceback (most recent call last):
File "G:\sdnext\OneTrainer\modules\ui\TrainUI.py", line 471, in __training_thread_function
trainer.start()
File "G:\sdnext\OneTrainer\modules\trainer\GenericTrainer.py", line 130, in start
self.model_setup.setup_model(self.model, self.config)
File "G:\sdnext\OneTrainer\modules\modelSetup\StableDiffusionFineTuneSetup.py", line 77, in setup_model
model.force_v_prediction()
File "G:\sdnext\OneTrainer\modules\model\StableDiffusionModel.py", line 173, in force_v_prediction
self.sd_config['model']['config']['parameterization'] = 'v'
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'config'
```
=> Fix prediction type change while training Stable Diffusion

modules/ui/ProfilingWindow.py, modules/ui/TrainUI.py, requirements-global.txt, start-ui.bat
We needed to get this diagnostic for a deadlock and most people are on Windows and unable to run normal profilers as a result. This is a quick workaround that should let us get a stack dump as long as the UI is able to run.
I put it to the right of "Export", but you might not like that, feel free to move the button wherever (or even have it trigger when you click the OneTrainer icon, so it's completely out of the way).
=> Add profiling section for CPU profiles and stack dump

modules/util/config/TrainConfig.py
Should prevent a whole host of complaints and help requests over memory issues.
=> Reduce default dataloader threads to 2.

modules/ui/ConceptTab.py, modules/util/ui/components.py
This PR adds support for wrapping text in labels within the concept widget boxes. Previously, long concept names would extend beyond the UI boundaries, causing display issues. The addition of the `wraplength` parameter to label components ensures that text is appropriately wrapped, maintaining the UI's integrity and improving readability.
=> Add support for long concept names in the concept tab

scripts/create_train_files.py
create_train_files script does not have explict `import os` and its using it which causes runtime errors on some python versions.
=> add missing import os

modules/modelSaver/PixArtAlphaLoRAModelSaver.py, modules/modelSaver/StableDiffusionLoRAModelSaver.py, modules/modelSaver/StableDiffusionXLLoRAModelSaver.py, modules/modelSaver/WuerstchenLoRAModelSaver.py, modules/modelSaver/pixartAlpha/PixArtAlphaLoRASaver.py, modules/modelSaver/stableDiffusion/StableDiffusionLoRASaver.py, modules/modelSaver/stableDiffusionXL/StableDiffusionXLLoRASaver.py, modules/modelSaver/wuerstchen/WuerstchenLoRASaver.py, modules/ui/TrainUI.py, modules/util/config/TrainConfig.py
This uses the format defined by https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13568. I tested it for SD1.5; I can't run any of the others on my machine so did not test those.
Currently A1111 only supports SD1.5/SD2/SDXL. There's no Wuerstchen or Pixart support in anything to actually use the bundled embeddings. That said, there was no reason to not extend the format to them.
I only write out the embeddings under `model.additional_embeddings` rather than anything in `model.additional_embedding_states`, with the idea that just because an embedding is present in training doesn't mean it should be shipped with the model. If I've misunderstood something about how `model.additional_embedding_states` is used, please correct me on this.
=> Optionally bundle joint-trained embeddings into LoRAs

modules/modelLoader/stableDiffusionXL/StableDiffusionXLModelLoader.py
`use_safetey_checker=False` is obsolete and removed in upcoming diffusers=0.28 (and now causes a runtime error)
`safety_checker=None` is recommended method that works in both old and new version of diffusers.
=> update safety checker skip in load

modules/ui/SampleFrame.py
Oops. This fixes #352.
The additional scrollbars aren't particularly pretty, but a11y kinda trumps looking nice I think.
=> Fix the sample window (from additional tools) messing up after a11y fixes.

modules/modelSetup/StableDiffusionEmbeddingSetup.py
A small fix for configuring vpred when training embeddings
I observed when training embeddings that the samples exhibited the behaviour of using a vpred model without having vpred enabled, even if Rescale Noise Schedule was enabled. So i investigated and found it was missing the lines present in the LoraSetup which setup vpred
=> fix embedding setup to use vpred if configured

modules/modelSetup/PixArtAlphaLoRASetup.py, modules/modelSetup/StableDiffusionLoRASetup.py, modules/modelSetup/StableDiffusionXLLoRASetup.py, modules/modelSetup/WuerstchenLoRASetup.py, modules/util/torch_util.py
Should work for any combination of:
* Train text encoder or not.
* Do not load a lora.
* Load a lora with a trained text encoder.
* Load a lora with an untrained text encoder.
Saves a (possibly significant) amount of output disk space.
=> Don't create TE layers that won't be trained or used.

modules/modelLoader/stableDiffusion/StableDiffusionModelLoader.py, modules/modelLoader/stableDiffusionXL/StableDiffusionXLModelLoader.py
Seems that model configs weren't loaded and always used default configs. Fixed by passing the model name to the function of the mixin.
=> fix model config loading for sd and sdxl

modules/ui/CaptionUI.py
It seems to have made things worse in a way that's difficult to understand, but is clearly causing regressions and problems for people. Making this zoomable etc. is going to be a larger and more difficult project.
=> Undo the a11y changes to the masks / caption UI.

modules/modelSampler/StableDiffusionVaeSampler.py
- `on_sample(image)` was missing so samples didn't render in gui in Sampling Tool
- resolution was not used so high resolution images used for sample where guaranteed OOM
- lines to match DecodeVAE implementation from MGDS (without it colors where off)
There are still some "burned" pixels on some of samples rendered in GUI using this code (example in attachment), I'll check tomorrow if they are visible after sampling to file while training.
=> VAE sampler fixes

Dockerfile
If this isn't specific, it can pull from any random registry instead. For example, Fedora machines have at least 3 matching container registries by default.
---
Notes:
- I don't know if the rest of the Dockerfile is still up-to-date. I decided not to use it.
- I also think that the installation of `nvidia-driver-525` inside the docker image looks very strange, since the whole point of NVIDIA's CUDA container images is that they have everything necessary inside the image already. I have made many containers based on NVIDIA's and never installed any specific driver inside them. They come with CUDA toolkit which in turn communicates with the latest NVIDIA driver on the host. That's the point. But hey, maybe I am wrong here.
- It also doesn't seem necessary to install any CUDA toolkit in the …
=> fix Dockerfile to specify which registry to pull from

.gitignore, LAUNCH-SCRIPTS.md, lib.include.sh
- We now default to installing Conda's environment in `conda_env` as a sub-directory of OneTrainer's project directory. This mirrors the behavior of our Python Venvs, and makes it much easier for users to remove the environment if they are uninstalling OneTrainer, since most users wouldn't know how to uninstall a system-wide Conda environment. This change also ensures that the environment will now be stored on the exact same disk as OneTrainer.
- The same flexibility as Python Venvs has been implemented, where you can now specify the absolute or relative path to an alternative Conda environment location via `OT_CONDA_ENV`. Paths with spaces are of course supported.
- All cleanup commands during manual Conda environment upgrades are now instructing the user about how to erase the locally …
=> Use project-local Conda environments for easier management and cleanup

modules/ui/CaptionUI.py, modules/util/ui/ui_utils.py
- Adds a unified helper function which binds the mouse-wheel correctly on every platform, and processes their platform-specific deltas into a unified format; "steps". The value is positive when scrolling up, and negative when scrolling down. And it now supports larger steps/deltas whenever the OS sends larger mouse events.
- The dataset mask editor's mouse-wheel radius adjustment now works on all platforms.
- Improved the mask radius calculation to ensure that it can never become smaller than 0.01, and made it behave like standard photo editors where "wheel up = zoom in/enlarge something, wheel down = zoom out/shrink something".
---
Tested:
=> Implement mouse-wheel support for Mac and Linux

modules/ui/CaptionUI.py, modules/util/ui/ui_utils.py
The recent refactor of mouse-wheel handling inadvertently made the lowest mask brush size a bit too big. This extends the lower range to allow very small brushes to be used.
Also fixes a small leftover import in related files.
=> Support very small brushes in the mask editor

README.md
FLUX.1 is a major feature which decides whether people try OneTrainer or not. It's been supported as a reliable feature for a long time now, so it's time to update the README, and to place it at the front for prominence. :)
=> Update README to mention that we support FLUX.1

modules/trainer/GenericTrainer.py, modules/ui/TrainUI.py, modules/util/config/TrainConfig.py, modules/util/ui/components.py
Automatic saving is used to have multiple checkpoints after training, so you can choose the best one.
However, you know in advance that the first x000 steps will not be the best one.
This PR adds a function to skip saving in those first x000 steps.
This example saves every 500 steps, but not within the first 3000:
Especially useful for full finetunes with large file sizes. The first few checkpoints waste both disk space and the time it takes to save.
=> added Skip Save interval before automatic saving starts

scripts/install_zluda.py, scripts/sample.py, scripts/util/import_util.py
This fixes the following issues:
- The old code inserted the "current working dir" into the module search paths, which has no correlation to the OneTrainer directory if the user executes the scripts with another active working directory. Now we use the actual OneTrainer directory regardless of its location, by leveraging the excellent Path library.
- The previous code inserted our path *last*, which meant that every import prioritized all other paths before looking in OneTrainer. This could lead to shadowing issues if a user has a system where a path contains another module named "modules", such as their own homemade project. We now insert ourselves at the top, as the highest priority.
- `scripts/install_zluda.py` was duplicating the efforts of importing modules. It clearly did that to …
=> Improve the module importer's robustness

lib.include.sh
NVIDIA uses a non-standard path for their WSL driver, which is documented here:
https://docs.nvidia.com/cuda/wsl-user-guide/
We now detect that special path too, so that OneTrainer's WSL users will automatically receive the NVIDIA CUDA dependencies.
This patch also removes the old "nvcc" check, which wasn't helpful, since it's not installed by default in NVIDIA drivers, and some people might have the CUDA SDK installed for software building purposes without having an NVIDIA GPU themselves.
=> Auto-detect NVIDIA GPUs inside Microsoft WSL

modules/ui/TrainingTab.py, modules/util/config/TrainConfig.py, modules/util/create.py
Changes "warmup steps" parameter from int to float. For input values >1 it behaves the same way as it did previously, warmup steps / gradient steps. For values between 0-1, it changes to warmup steps * total steps (total steps already compensates for gradient accumulation). Any other values will be set to zero. Also modified mouseover text to reflect that change.
Some examples of behavior, tested with total steps 100. Also verified warmup behavior correctly works for different gradient accumulation values, though I did come across an issue related to changing that value while training is running (see issue #557):
- Warmup set to 50 = 50 steps of warmup, 50 steps of scheduler
- Warmup set to 0.4 = 40 steps of warmup, 60 steps of scheduler
- Warmup set to -0.3 = 0 steps of warmup, 100 steps …
=> Warmup steps allows values <1 as percentage of total

update.bat
Certain requirements can complain if pip or setuptools are outdated. Updating pip and setuptools first will avoid that risk.
I've personally seen a OneTrainer dependency fail to install when setuptools was outdated. It's used when installing dependencies that build themselves from source.
Having the latest pip also avoids some issues since they frequently fix bugs. I've seen dependencies that couldn't resolve until pip was updated.
Those tools (pip and setuptools) must be installed in a separate step before the requirements.txt, to take effect.
Added `--upgrade` flag too, which I am pretty sure needs to be there (since `--upgrade-strategy` is a modifier for the `--upgrade` mode).
This now matches the Linux commands:
https://github.com/Nerogar/OneTrainer/blob/b5699f51c070c15c9aac340d5967fd6 …
=> update.bat: update pip before the requirements

modules/trainer/GenericTrainer.py
* backup, save: Take a callback function to handle emitting output.
This allows things like tqdm.write to be passed in. Previously
with print being used it would emit output like "Creating backup"
at the end of the tqdm bar and then continue to the next line,
munging/overlapping output. Depending on how often one creates
backups or saves, it can result in the epoch line being clobbered
every single cycle and/or a portion of it being emitted into
scrollback repeatedly.
=> GenericTrainer: Fix inconsistent output

modules/ui/TopBar.py
Adds a button to be able to quickly go to the wiki of OneTrainer.
Adds webbrowser to topbay.py and moves the columns 1 to the right for the model and training type.
=> Add wiki button to the Top Bar of the UI

modules/ui/OptimizerParamsWindow.py, modules/util/config/TrainConfig.py, modules/util/create.py, modules/util/optimizer_util.py, requirements-global.txt
Support new hyperparameter in Prodigy optimizer that reduces vram usage by about half.
Wait with merge until the prodigyopt package is updated in PyPi.
In this PR I've chosen to enable it by default, while the package maintainers have chosen to disable it by default in order to not change the behaviour.
This is debatable, but I think we can be a bit less careful: We haven't found a case yet in which Prodigy performs worse when this is enabled. In my own tests, in tests by a team of testers on Discord, and in original experiments of the Prodigy paper, repeated by the original authors. Details here: https://github.com/konstmish/prodigy/pull/22
I can disable it by default though if you prefer
=> Support slice_p in Prodigy optimizer

.gitignore, LAUNCH-SCRIPTS.md, lib.include.sh
OneTrainer's self-update process now supports source-aware updates via an opt-in flag, which skips the update check if the OneTrainer source code hasn't changed.
This optimization significantly speeds up executions of `update.sh`.
While generally safe, this approach may miss some updates and critical bug fixes for third-party dependencies.
By default, this feature is disabled to ensure maximum safety.
Closes: #637
=> Implement source-aware updates to speed up dependency checks

modules/trainer/GenericTrainer.py, modules/ui/TrainingTab.py, modules/util/config/TrainConfig.py, modules/util/create.py, modules/util/lr_scheduler_util.py
I implemented a new training parameter for use with cosines, linear, and REX. 
The `learning_rate_min_factor` sets the lower limit of the LR. If the initial LR is `2e-4` and you set a `learning_rate_min_factor` of `0.5`, the final LR value will be `1e-4`. 
Basically, the final LR equals the initial LR multiplied by the factor.
=> learning_rate_min_factor

modules/modelSetup/BaseFluxSetup.py, modules/modelSetup/BaseHunyuanVideoSetup.py, modules/modelSetup/BaseModelSetup.py, modules/modelSetup/BasePixArtAlphaSetup.py, modules/modelSetup/BaseSanaSetup.py, modules/modelSetup/BaseStableDiffusion3Setup.py, modules/modelSetup/BaseStableDiffusionSetup.py, modules/modelSetup/BaseStableDiffusionXLSetup.py, modules/modelSetup/BaseWuerstchenSetup.py, modules/trainer/GenericTrainer.py
See https://github.com/spacepxl/demystifying-sd-finetuning for more context on why this is helpful. TL;DR, it takes the validation loss from this:
to this:
by seeding the validation process the same way each time it's run, so the only changing variable is the trained model.
This pr is just a very basic version, using the existing deterministic timestep option to lock timestep to 500, and overriding the seed to 0, but a better implementation would just seed once at the start of validation, and use different timesteps and noise for each image sampled, to be more robust. Unfortunately I couldn't find a way to stop the validation dataloader from shuffling, but this version is already more useful than the previous fully random validation.
=> Make validation deterministic

modules/cloud/LinuxCloud.py, modules/modelSampler/BaseModelSampler.py, modules/trainer/CloudTrainer.py, modules/ui/CloudTab.py, modules/ui/TrainUI.py, scripts/train_remote.py
Various improvements for cloud:
- bugfix: updating cloud id, host and port in the UI didnt work anymore since switch to SecretsConfig
- use OT_LAZY_UPDATES  see https://github.com/Nerogar/OneTrainer/pull/643
- UI improvements
- UI button to create RunPods on website
- automatically replace train device `cpu` with `cuda`: cpu is the default if there is no GPU found on the client PC that runs OneTrainer. But using `cpu` on cloud is not intended
- improve samples pickling
Collected over a while - submitting them now because the last point is a fix to a breaking change
=> Various Cloud improvements

modules/ui/ConceptTab.py, modules/ui/ConceptWindow.py
Image preview for concepts now looks in subdirectories if option is enabled, in both the concept tab and concept window. Tested with files in the top level and nested subdirectories and works as expected, no noticeable lag when previewing a concept folder with several thousand images.
Adds fields in concept window to display the name of the previewed file and the associated caption, depending on prompt source. Currently only displays the "unmodified" caption before shuffling/dropout, and only the first line if a file has multiple captions. Will try to change this to preview the "modified" caption in the future.
=> Image preview from subdirectories, filename/caption preview

modules/modelSampler/FluxSampler.py, modules/modelSetup/BaseFluxSetup.py, modules/modelSetup/BaseStableDiffusion3Setup.py, modules/modelSetup/mixin/ModelSetupNoiseMixin.py, modules/ui/TimestepDistributionWindow.py, modules/ui/TrainingTab.py, modules/util/config/TrainConfig.py
This is an implementation of timestep shifting for training, as is done by `FlowMatchEulerDiscreteScheduler` during inference.
An explanation why I think this is correct you can find here: https://github.com/Nerogar/OneTrainer/issues/615
I am getting more and more convinved of this, because many of my own training experiments have failed or would have failed if I didn't manually mess with the timestep distribution first. The default timestep distribution often cannot change the image composition enough.
New training parameters:
This PR doesn't change any defaults, but I believe this should be the defaults for the presets:
SD3: timestep_shift = 3.0
Flux: dynamic_timestep_shifting = True
Here are some examples:
LOGIT_NORMAL distribution with timestep_shift == 1.8, which is what dynamic …
=> Timestep shifting

modules/trainer/GenericTrainer.py, modules/ui/TrainUI.py, modules/util/config/TrainConfig.py
Just a QoL option that makes OT skip sample generation when training starts.
I’ve been annoyed by this for a long time, always having to enable and disable samples at the start of each training session. 😉
=> Skip samples on training start

scripts/util/version_check.py
- The `%` technique is Python's oldest format string syntax, so it's more backwards-compatible than `str.format()`.
- Using `sys.stderr.write()` allows us to output directly to stderr in a backwards-compatible way.
Verified on Python 2.5.6 from almost 20 years ago.
---
Example output:
```
Error: Your Python version is too low: 2.5.6 (r256:88840, Feb 22 2025, 23:16:06) 
[GCC 14.2.1 20250110 (Red Hat 14.2.1-7)]. Must be >= 3.10 and < 3.13.
```
---
Thanks to @O-J1 for suggesting `sys.stderr.write()`.
=> improve Python version check backwards compatibility

modules/modelSampler/FluxSampler.py, modules/modelSampler/StableDiffusionSampler.py, modules/modelSampler/StableDiffusionXLSampler.py, modules/module/BaseImageCaptionModel.py, modules/module/BaseImageMaskModel.py, modules/ui/CaptionUI.py, modules/ui/ConceptTab.py, modules/ui/ConceptWindow.py, modules/util/concept_stats.py, modules/util/image_util.py
When uploading photos with EXIF metadata (e.g. captured with iPhone), current OT implementation doesn't handle rotation flags, leading to photos being processed in wrong orientation (e.g. when creating masks):
This fix adds EXIF metadata handling in all the necessary places (I hope):
=> Add EXIF metadata handling

install.bat, scripts/util/version_check.py
Adjusts logic to work with windows store python installs. Tested with windows store install and then tested again the proper way both worked.
Also added specific exclusion for 3.11.0 as Scalene is explitctly not compatible with this version
Resolves #761
=> Allow Windows Store installs + mark 3.11.0 installs as specifically not supported in version_check

modules/module/LoRAModule.py, modules/ui/LoraTab.py, modules/util/config/TrainConfig.py
Based on https://github.com/KohakuBlueleaf/LyCORIS/issues/216
Adds an option to apply the decomposition on the output axis instead of the input axis
=> Add option to apply DoRA on output axis

modules/cloud/LinuxCloud.py
Code comment:
#many docker images, including the default ones on RunPod and vast.ai, only set up $PATH correctly
#for interactive shells. On RunPod, cuda is missing from $PATH; on vast.ai, python is missing.
#We cannot pretend to be interactive either, because then vast.ai starts a tmux screen.
#Add these paths manually
It was set manually before too, but only for RunPod.
=> Cloud: support for vast.ai

modules/trainer/GenericTrainer.py
for A/B tests I use the same workspace, to have all of them in tensorboard. 
I tend to mix up samples and don't remember to which run they belonged to, especially when running multiple OneTrainers at the same time on clouds. We already use the prefix for saves and for tensorboard. Can we use it for samples, too?
=> use save prefix for samples

modules/cloud/RunpodCloud.py, modules/modelSetup/BaseFluxSetup.py
Container size needs to be higher than 10 GB to allow for large updates such as pytorch.
Unfortunately, this default size, that is (only) used when a cloud instance is created through the API, had to be hardcoded because of a bug in the RunPod API: https://github.com/runpod/runpod-python/issues/386
That's why this is a code change, not only a change in the container template on RunPod
=> Increase default container size for RunPod

install.bat, requirements-global.txt
Tested locally on windows 10 and 11 with 3.13, 3.12 and 3.11 install. Shifted to using `py` first, and using `pushd`, `popd` and `call`, the previous approach was very annoying to extend.
The reason this came up is (stupidly) there is 'commercial' software supposedly (according to a user) requiring python 3.13. I wont name incase it was incorrect but regardless, we now check py launcher versions, loop through and check with version_check.py
=> Extend Install.bat to work better with multiple versions of python

modules/zluda/ZLUDA.py
Trying to dry run this on macos failed with the following error 
```bash
Exception in thread Thread-1 (__training_thread_function):
Traceback (most recent call last):
File "${home}/.pyenv/versions/3.12.11/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "${home}/.pyenv/versions/3.12.11/lib/python3.12/threading.py", line 1012, in run
self._target(*self._args, **self._kwargs)
File "${home}/code/OneTrainer/modules/ui/TrainUI.py", line 597, in __training_thread_function
ZLUDA.initialize_devices(self.train_config)
File "${home}/code/OneTrainer/modules/zluda/ZLUDA.py", line 37, in initialize_devices
if not is_zluda(config.train_device) and not is_zluda(config.temp_device):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "${home}/code/OneTrainer/modules/zluda/ZLUDA.py", line 12, …
```
=> add mps filter to ZLUDA check

modules/ui/AdditionalEmbeddingsTab.py, modules/ui/ConceptTab.py, modules/ui/ConfigList.py, modules/ui/SamplingTab.py, modules/util/ui/components.py
Saw a couple people talking about a 'disable all' button for the concept and sampling tabs and decided to update `ConfigList` to have a couple configurable attributes to allow this. Seemed minor so I opted not to create a discussion, but I can open one if needed.
Concepts tab:
Sampling tab:
Additional embeddings tab:
Scheduler params window (unchanged):
=> ConfigList - add 'enable/disable' and 'enable all/disable all' buttons

modules/modelSampler/ChromaSampler.py, modules/modelSampler/FluxSampler.py, modules/modelSampler/HiDreamSampler.py, modules/modelSampler/HunyuanVideoSampler.py, modules/modelSampler/PixArtAlphaSampler.py, modules/modelSampler/SanaSampler.py, modules/modelSampler/StableDiffusion3Sampler.py, modules/modelSampler/StableDiffusionSampler.py, modules/modelSampler/StableDiffusionXLSampler.py
It should fix all samplers for v_prediction/zero-terminal SNR models with standard models. Most likely that's just step that most schedulers do on it's own so we did end up with duplicated step.
Models using squaredcos_cap_v2 scheduler still won't sample with kerras scheduler as sigmas are rounded that's why depending on model timesteps off-by one error can still appear with those models. Fixing it would require rewritting some sampling code, but that's chunk of work for models that do not exist.
=> Fix for off-by-one error with v_prediction

modules/trainer/GenericTrainer.py
Fixes #327
Decided to split this fix out of Dataset Tools rework given its immense size.
=> Graceful fail for sampling if config becomes corrupted or missing after training 

modules/modelLoader/stableDiffusionXL/StableDiffusionXLModelLoader.py, modules/modelSetup/BaseFluxSetup.py
#934 and #776 describe how FP8 training on SDXL requires more vram than expected.
Steps why this change https://github.com/Nerogar/OneTrainer/pull/989/files#diff-eaab6bd7bca752fedce03a486d2e1b8724eb9a0358dbebae493bde074d35fe8d fixes that:
- diffusers.StableDiffusionXLPipeline does not have a `text_encoder_1` property. Text encoder 1 is just named just `text_encoder`.
- This raises a python exception
- All exceptions are caught here https://github.com/Nerogar/OneTrainer/blob/12d1812db22c6ec32c1001e3886bfe7d8918d078/modules/modelLoader/stableDiffusionXL/StableDiffusionXLModelLoader.py#L258
- Loading as safetensors failed, we continue with trying to load as ckpt
- __load_ckpt successfully loads the file, even though it is a safetensors file, because it uses the same diffusers API calls that …
=> Bugfix for #934 and #776
