Nerogar/OneTrainer

modules/trainer/GenericTrainer.py
fix a tensorboard bug that can not show log correctly when trained in a same workspace repeatedly
=> fix a tensorboard bug

modules/module/BaseImageMaskModel.py, modules/module/ClipSegModel.py, modules/module/MaskByColor.py, modules/module/RembgModel.py, modules/ui/GenerateMasksWindow.py, modules/util/args/GenerateMasksArgs.py, requirements.txt, scripts/generate_masks.py
It's currently unknown to me whether this will be supported during training.
=> Enable generation of non-binary masks.

modules/util/create.py, modules/util/enum/LearningRateScheduler.py
Allows Adafactor to log LR properly.
=> Add Adafactor scheduler

requirements.txt
=> Ensure PyTorch compatible with xformers is fetched.

install.sh, requirements.txt, start-ui.sh, update.sh
Adds simple bash scripts, for me as a Anaconda3 user it's working, so i have not yet ~~completed~~ tested "native" python venv creation and usage and can not test these well. 
Either use AS IS and wait for someone else to fix that, or wait first, merge then.
As stated in my first comment the workdir creation part is yet to be done, either via the command (which failed on me) or by manually using mkdir.
I encourage Linux users to test this, and suggest improvements.
see #41
=> add Linux bash scripts

Dockerfile, docs/DockerImage.md
Dockerfile based on nvidia/cuda:11.8.0-devel-ubuntu22.04
Rough docs for building image and running from image.
Fixes #64
=> Provides a Dockerfile and example build instructions

modules/trainer/GenericTrainer.py, modules/ui/TrainUI.py, modules/util/args/TrainArgs.py
Adds a toggle and parameter to bind TB to all interfaces (make it accessible from external network vs. just localhost).
Hopefully i didn't mess something up.
=> Add option to bind Tensorboard to all interfaces

modules/ui/CaptionUI.py
Added a text box to let you change the alpha value that is used when you are drawing in masks by hand.
Also changed the mask display over the image to normalize the values instead of clipping so that you can see lower alpha values in the alpha image.
=> Set alpha for your mask brush in manual edit mode

modules/module/BaseImageCaptionModel.py, modules/module/BaseImageMaskModel.py, modules/ui/CaptionUI.py, modules/ui/GenerateCaptionsWindow.py, modules/ui/GenerateMasksWindow.py, modules/ui/TrainUI.py, modules/util/args/CaptionUIArgs.py, modules/util/args/GenerateCaptionsArgs.py, modules/util/args/GenerateMasksArgs.py, modules/util/ui/components.py, scripts/caption_ui.py, scripts/generate_captions.py, scripts/generate_masks.py
Enable Image captioning to include subdirs in it, if specified.
```bash
python .\scripts\generate_captions.py --model WD14_VIT_2 --sample D:\sd\dataset\ds_org --include-subdirectories
python .\scripts\generate_masks.py --sample-dir D:\test --model CLIPSEG --add-prompt test --include-subdirectories 
```
=> feature. enable image captioning to include subfolders

modules/modelSetup/BasePixArtAlphaSetup.py, modules/modelSetup/BaseStableDiffusionSetup.py, modules/modelSetup/BaseStableDiffusionXLSetup.py, modules/modelSetup/BaseWuerstchenSetup.py, modules/modelSetup/mixin/ModelSetupDiffusionNoiseMixin.py, modules/ui/TrainingTab.py, modules/util/args/TrainArgs.py, modules/util/ui/ToolTip.py, modules/util/ui/components.py
This adds three new parameters:  min noising strength, noising weight, and noising bias.  The min noising strength works with max noising strength to control the range of time steps being trained.  The noising weight and bias utilize a sigmoid function to control the distribution of time steps.  This can be used to focus training on high or low frequency details.
=> Add Min Noising Strength, Noising Weight, Noising Bias parameters

modules/util/create.py
=> Prodigy is not Adafactor anymore.

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml
As recommended by: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
=> Add issue templates.

.gitignore, install.sh, modules/modelSetup/mixin/ModelSetupDiffusionLossMixin.py, modules/trainer/GenericTrainer.py, modules/ui/CaptionUI.py, modules/ui/ConvertModelUI.py, modules/util/args/GenerateCaptionsArgs.py, modules/util/args/GenerateMasksArgs.py, modules/util/config/TrainConfig.py, modules/util/dtype_util.py, modules/util/torch_util.py, requirements-cuda.txt, requirements-default.txt, requirements-global.txt, requirements-rocm.txt, requirements.txt, scripts/sample.py, start-ui.sh, update.bat, update.sh
Also need this small change in MGDS:
```diff
diff --git a/src/mgds/PipelineModule.py b/src/mgds/PipelineModule.py
index 184f911..0195b0c 100644
--- a/src/mgds/PipelineModule.py
+++ b/src/mgds/PipelineModule.py
@@ -148,9 +148,18 @@ class PipelineModule(metaclass=ABCMeta):
return Random(seed)
def _torch_gc(self):
-        torch.cuda.synchronize()
+        if torch.cuda.is_available():
+            torch.cuda.synchronize()
+        if torch.backends.mps.is_available():
+            torch.mps.synchronize()
+        
gc.collect()
-        torch.cuda.empty_cache()
+        
+        if torch.cuda.is_available():
+            torch.cuda.empty_cache()
+        
+        if torch.backends.mps.is_available():
+            torch.mps.empty_cache()
@abstractmethod
def length(self) -> int:
```
=> Allow for MPS/ROCm training.

modules/dataLoader/mixin/DataLoaderMgdsMixin.py, modules/ui/TrainUI.py, modules/util/config/TrainConfig.py, requirements-global.txt
Adds support for concurrent dataloading with a user-configurable number of threads. Needs [MGDS support](https://github.com/Nerogar/mgds/pull/3) to be merged first.
=> Parallel dataloader support

modules/trainer/GenericTrainer.py, modules/ui/OptimizerParamsWindow.py, modules/util/config/TrainConfig.py, modules/util/create.py, modules/util/enum/Optimizer.py, modules/util/optimizer_util.py, requirements-global.txt
Closes #239.
Not completely happy with the need to add special-case logic. As mentioned in the comments I left, this is a good candidate for a future callback refactoring.
=> Implement Facebook's new schedule-free optimizers.

modules/model/PixArtAlphaModel.py, modules/modelLoader/PixArtAlphaEmbeddingModelLoader.py, modules/modelLoader/PixArtAlphaFineTuneModelLoader.py, modules/modelLoader/PixArtAlphaLoRAModelLoader.py, modules/modelSampler/PixArtAlphaSampler.py, modules/modelSaver/pixartAlpha/PixArtAlphaModelSaver.py, modules/ui/ConvertModelUI.py, modules/ui/ModelTab.py, modules/ui/TopBar.py, modules/ui/TrainingTab.py, modules/util/convert/convert_pixart_diffusers_to_ckpt.py, modules/util/create.py, modules/util/enum/ModelType.py, requirements-global.txt, resources/sd_model_spec/pixart_sigma_1.0-embedding.json, resources/sd_model_spec/pixart_sigma_1.0-lora.json, resources/sd_model_spec/pixart_sigma_1.0.json
It's basically the same as alpha. Uses all the same infrastructure, with one switch between pipeline loading. The sampler was changed slightly to match what diffusers does.
=> Implement Pixart Sigma

modules/modelSampler/StableDiffusionSampler.py, modules/modelSetup/BaseStableDiffusionSetup.py
To close https://github.com/Nerogar/OneTrainer/issues/402
tested on:
sd15_inpaint_weight_bf16_debug_sampling_inpainting_masked_training
sd15_inpaint_weight_bf16_debug_sampling_inpainting
sd15_inpaint_weight_f16_debug_sampling_inpainting_masked_training
sd15_inpaint_weight_f16_debug_sampling_inpainting
=> Fix errors with float16

modules/module/LoRAModule.py, modules/ui/LoraTab.py, modules/util/config/TrainConfig.py
This restores (as an option) DoRA as implemented by Lycoris and tested by us before. Empirically it seems to have much better results in some circumstances.
=> Optional epsilon for weight decompose.

modules/modelSetup/mixin/ModelSetupDiffusionLossMixin.py, modules/ui/TrainingTab.py, modules/util/config/TrainConfig.py
Add Log - Hyperbolic cosine loss.
Relevant links:
https://www.tensorflow.org/api_docs/python/tf/keras/losses/LogCosh
https://openreview.net/forum?id=rkglvsC9Ym
https://datascience.stackexchange.com/questions/96271/logcoshloss-on-pytorch
=> Add log-cosh loss

modules/dataLoader/FluxBaseDataLoader.py, modules/dataLoader/PixArtAlphaBaseDataLoader.py, modules/dataLoader/StableDiffusion3BaseDataLoader.py, modules/dataLoader/StableDiffusionBaseDataLoader.py, modules/dataLoader/StableDiffusionFineTuneVaeDataLoader.py, modules/dataLoader/StableDiffusionXLBaseDataLoader.py, modules/dataLoader/WuerstchenBaseDataLoader.py, modules/dataLoader/mixin/DataLoaderMgdsMixin.py, modules/trainer/BaseTrainer.py, modules/trainer/GenericTrainer.py, modules/ui/ConceptWindow.py, modules/ui/TrainUI.py, modules/util/config/ConceptConfig.py, modules/util/config/TrainConfig.py, modules/util/create.py
Simple validation logic was implemented
ValidationBaseDataLoader class is added. This class is primarily a clone of StableDiffusionBaseDataLoader with an added boolean variable validation in the create_dataset method.
To process new variable and divide train and validation datasets DataLoaderMgdsMixin was modified. 
UI was updated to provide radio buttons for validation logic.  
It's hard to consider that PR ready to merge. I suggest we discuss this further to ensure alignment with your future plans.
=> Validation implementing

modules/ui/ConceptWindow.py
=> Fixed tooltip

modules/ui/TopBar.py
Have the dropdown menu show configs in sorted order
=> Sort config list

modules/cloud/BaseCloud.py, modules/modelSaver/mixin/DtypeModelSaverMixin.py, modules/trainer/CloudTrainer.py, modules/trainer/GenericTrainer.py, modules/ui/TopBar.py, modules/ui/TrainUI.py, modules/util/config/TrainConfig.py
fix to https://github.com/Nerogar/OneTrainer/pull/619
=> Secrets fix

modules/util/enum/Optimizer.py
adding prodigy dlr on tensorboard
=> adding prodigy dlr on tensorboard

modules/modelSetup/BaseFluxSetup.py, modules/modelSetup/BaseHunyuanVideoSetup.py, modules/modelSetup/BasePixArtAlphaSetup.py, modules/modelSetup/BaseSanaSetup.py, modules/modelSetup/BaseStableDiffusion3Setup.py, modules/modelSetup/BaseStableDiffusionSetup.py, modules/modelSetup/BaseStableDiffusionXLSetup.py, modules/modelSetup/BaseWuerstchenSetup.py
Small fix for #660 to make the code less bulky.
=> Simplify batch_seed assignment

modules/ui/OptimizerParamsWindow.py, modules/util/config/TrainConfig.py, modules/util/create.py, modules/util/enum/Optimizer.py, modules/util/optimizer_util.py
Add Yogi optimizer with adaptive moment estimation that can both increase and decrease its accumulator, preventing over-accumulation compared to Adagrad/Adam.
=> Add Yogi optimizer

scripts/README.md
For new users who dont know onetrainer, and are only interested in using the scripts, adding the direct link here can 
save a lot of time for them.
=> Doc link for scripts dir

modules/ui/CaptionUI.py, modules/ui/ConceptWindow.py, modules/ui/ConvertModelUI.py, modules/ui/GenerateCaptionsWindow.py, modules/ui/GenerateMasksWindow.py, modules/ui/OffloadingWindow.py, modules/ui/OptimizerParamsWindow.py, modules/ui/ProfilingWindow.py, modules/ui/SampleParamsWindow.py, modules/ui/SampleWindow.py, modules/ui/SchedulerParamsWindow.py, modules/ui/TimestepDistributionWindow.py, modules/ui/TrainUI.py, modules/util/ui/dialogs.py, modules/util/ui/ui_utils.py
The sample window was broken by a duplicate wait for visibility + there was an incorrectly triggered try that should have been skipped using platform. 
Additionally formatted (re-ordered) the inits to make them easier to parse. Dxqb and sakurairisis tested and found the bugfix worked.
=> Bugfix + Further Icon tweaks - tested working

modules/cloud/BaseCloud.py, modules/cloud/LinuxCloud.py, modules/cloud/RunpodCloud.py, modules/ui/CloudTab.py, modules/util/config/CloudConfig.py
- https://github.com/Nerogar/OneTrainer/issues/758
- set keepalive for main SSH connection - helps Windows detect connection loss faster
- remove Jupyter password: Runpod now automatically sets the token when you open Jupyter, it is no longer needed to enter a password.
=> Cloud various

modules/dataLoader/mixin/DataLoaderMgdsMixin.py
I hadn't seen @dxqbYD's pull request so wrote my own version. Feel free to just decline this one, or accept it if you prefer this way of refactoring the code. I've tested both code paths, both work.
=> Fixed validation concepts bug

modules/model/WuerstchenModel.py
* This was broken by refactoring work done in 6fc0d74d.
=> Fix cascade helper naming problem

modules/ui/ConceptWindow.py
Added threading for concept scan functions, changed the way GUI is updated to hopefully be thread-safe. Large single folders should no longer hold up the GUI when concept is loaded
Add check to make sure concept path is a valid directory before getting stats https://github.com/Nerogar/OneTrainer/issues/767
=> fix concept stats GUI

modules/model/StableDiffusionModel.py
This is a partial fix for #624 
Borrowed from Heasterian's branch, who mentioned that a global fix for this problem is problematic.
But cleaning up this hardcode bug in SD1.5 support is straightforward, at least.
=> Make token limit dynamic for SD1.5

modules/modelSetup/BaseFluxSetup.py, training_presets/#chroma Finetune 16GB.json, training_presets/#chroma Finetune 24GB.json, training_presets/#chroma Finetune 8GB.json
- appropriate LR for full finetuning
- include optimizer presets, otherwise they are not used
=> fix Chroma presets

modules/modelSampler/ChromaSampler.py, modules/modelSampler/FluxSampler.py, modules/modelSampler/HiDreamSampler.py, modules/modelSampler/HunyuanVideoSampler.py, modules/modelSampler/PixArtAlphaSampler.py, modules/modelSampler/SanaSampler.py, modules/modelSampler/StableDiffusion3Sampler.py, modules/modelSampler/StableDiffusionSampler.py, modules/modelSampler/StableDiffusionXLSampler.py, modules/modelSampler/WuerstchenSampler.py, modules/modelSetup/PixArtAlphaFineTuneSetup.py, modules/modelSetup/SanaFineTuneSetup.py, modules/ui/TrainingTab.py
see https://github.com/Nerogar/OneTrainer/pull/965
=> Fix for off-by-one error with v_prediction

modules/util/torch_util.py
Fix #683 
Added a comment by Nero after he explained a portion of tensors_record_stream() worked in dm's
=> Minor fix + Nero's comment

modules/cloud/RunpodCloud.py, modules/modelSetup/BaseFluxSetup.py
adjust to breaking RunPod web API change
=> adjust to breaking RunPod web API change
